name: Deploy to gh-page

on:
  push:
    branches:
      - master # default branch

jobs:
  deploy-gh-page:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: pnpm/action-setup@v2
        with:
          version: 7
          run_install: false
      - uses: actions/setup-node@v3
        with:
          node-version: "16"
          cache: "pnpm"
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
      - name: Build
        run: npm run build
      - name: Deploy to gh-page
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public

  deploy-to-server:
    runs-on: ubuntu-latest
    needs: [deploy-gh-page]
    steps:
      - name: Deploy to server
        uses: wei/git-sync@v3
        with:
          source_repo: JakeLaoyu/blog
          source_branch: refs/remotes/source/gh-pages
          destination_repo: root@110.40.198.64:/www/wwwroot/blog.git
          destination_branch: refs/heads/master
          destination_ssh_private_key: ${{ secrets.SERVER_PRIVATE_KEY }} # optional, will override `SSH_PRIVATE_KEY`
