name: release

on:
  push:
    branches: 
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - uses: pnpm/action-setup@v4
        name: Install pnpm
        with:
          version: 8
          run_install: false

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: "18.x"
          cache: 'pnpm'
          
      - name: Install hexo dependencies && Generate files
        run: pnpm install && pnpm run build
      - name: Install coscmd
        run: sudo pip install coscmd
      - name: Configure coscmd
        env:
          SECRET_ID: ${{ secrets.SecretId }}
          SECRET_KEY: ${{ secrets.SecretKey }}
          BUCKET: ${{ secrets.Bucket }}
          REGION: ${{ secrets.Region }}
        run: coscmd config -a $SECRET_ID -s $SECRET_KEY -b $BUCKET -r $REGION
        
      - name: Upload
        run: cd ./public && coscmd upload -r ./ /

      - name: Refresh CDN
        run: node ./tencent.js
        env:
          TENCENT_SECRET_ID: ${{secrets.SecretId}}
          TENCENT_SECRET_KEY: ${{secrets.SecretKey}}
