name: Sync to Coding

on:
  push:
    branches: [master, v1]

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Sync to Coding
        uses: wearerequired/git-mirror-action@master
        env:
          # 在 Settings->Secrets 配置 GITEE_RSA_PRIVATE_KEY
          SSH_PRIVATE_KEY: ${{ secrets.GITEE_RSA_PRIVATE_KEY }}
        with:
          # GitHub 源仓库地址
          source-repo: git@github.com:JakeLaoyu/blog.git
          # Gitee 目标仓库地址
          destination-repo: git@e.coding.net:JakeLaoyu/HexoBlogBackup.git
